services:
  prism:
    image: stoplight/prism:4
    command: 'mock -h 0.0.0.0 /tmp/openapi.yml'
    volumes:
      - ./openapi/openapi.yml:/tmp/openapi.yml
    ports:
      # Serve the mocked API locally as available on port 8301
      - '8301:4010'
  redoc:
    image: redocly/redoc
    volumes:
      - ./openapi:/usr/share/nginx/html/api
    environment:
      SPEC_URL: api/openapi.yml
    ports:
      - 8080:80
  openapi_generator:
    image: openapitools/openapi-generator-cli:v6.6.0
    volumes:
      - ./:/local
    command: generate -i local/openapi/openapi.yml -g typescript-axios -o local/tanstack_prism_generouted_example/types